// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdjkfoxjahpzpigxnypc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkamtmb3hqYWhwenBpZ3hueXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NzQ3NDcsImV4cCI6MjA3NTM1MDc0N30.AB4siG9BkrcQGAiCUGuaj58n4XZKCKlyFSlo7AtGvJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});